# 1. Importação de bibliotecas

In [1]:
import pandas as pd
import random

# 2. Leitura dos dados

In [4]:
df = pd.read_csv("launch_telemetry_data.csv")
df.head()

,internal_temp,external_temp,structural_integrity,energy_level,tank_pressure,critical_modules
0,22,15,1,85,250,OK
1,30,40,1,90,260,OK
2,10,-20,1,88,240,OK
3,5,-50,1,80,200,OK
4,35,50,1,95,300,OK

# 3. Visualização dos dados

In [4]:
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   internal_temp         20 non-null     int64
 1   external_temp         20 non-null     int64
 2   structural_integrity  20 non-null     int64
 3   energy_level          20 non-null     int64
 4   tank_pressure         20 non-null     int64
 5   critical_modules      20 non-null     str
dtypes: int64(5), str(1)
memory usage: 1.1 KB

,internal_temp,external_temp,structural_integrity,energy_level,tank_pressure
count,20.000000,20.000000,20.000000,20.000000,20.00000
mean,22.450000,10.450000,0.950000,84.600000,245.95000
std,10.086338,32.498542,0.223607,4.581427,33.69597
min,5.000000,-55.000000,0.000000,75.000000,180.00000
25%,17.250000,3.750000,1.000000,81.750000,227.50000
50%,20.000000,10.000000,1.000000,85.000000,250.00000
75%,30.750000,28.750000,1.000000,85.500000,252.50000
max,40.000000,60.000000,1.000000,95.000000,310.00000

# 4. Verificação para decolagem

In [2]:
def check_launch(row):
    if row["structural_integrity"] != 1:
        return "ABORTED: structural failure"

    if row["energy_level"] < 80:
        return "ABORTED: low energy"

    if not (5 <= row["internal_temp"] <= 35):
        return "ABORTED: internal temperature out of range"

    if not (-50 <= row["external_temp"] <= 50):
        return "ABORTED: external temperature out of range"

    if not (200 <= row["tank_pressure"] <= 300):
        return "ABORTED: tank pressure out of range"

    if row["critical_modules"] != "OK":
        return "ABORTED: failure on critical modules"

    return "READY FOR LAUNCH"

# 5. Aplicação da função de verificação

In [12]:
random_index = random.randint(0, len(df) - 1)
random_row = df.iloc[random_index]

result = check_launch(random_row)

print("Selected telemetry reading:")
print(random_row)
print("\nLaunch decision:")
print(result)

Selected telemetry reading:
internal_temp            20
external_temp            20
structural_integrity      1
energy_level             80
tank_pressure           200
critical_modules         OK
Name: 19, dtype: object

Launch decision:
READY FOR LAUNCH